Newbranch
DavidPerezS/JSexamplescodes pull request #4
Opened 2021-03-10 20:21 UTC by DavidPerezS

3 exercises solving leap year and Sebastian´s issues.

2021-03-11 13:48 UTC, Thormod commented on exercise_2/index.js
> +const { get } = require('prompt');
Remove unused module.

2021-03-11 13:48 UTC, Thormod commented on leapyear.js
>  const prompt = require('prompt-sync')();
Let's create a folder and name it `exercise_0`

2021-03-11 19:11 UTC, salorrego commented on .gitignore
> +node_modules
EOF

2021-03-11 19:11 UTC, salorrego commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/node,visualstudiocode,windows
please add EOF (a blank line at the end of the file so you can read it easily at the end)

2021-03-15 16:08 UTC, Thormod requested changes

2021-03-15 16:08 UTC, Thormod commented on exercise_3/index.js
> +    await getJoke()
```suggestion
    await getJoke(searchparam)
```

2021-03-15 16:08 UTC, Thormod commented on exercise_3/index.js
> +const getJoke = async () => {
```suggestion
const getJoke = async (searchParam) => {
```

2021-03-15 16:08 UTC, Thormod commented on exercise_3/index.js
> +      `https://icanhazdadjoke.com/search?term=${searchparam}`,
```suggestion
      `https://icanhazdadjoke.com/search?term=${searchParam}`,
```

2021-03-15 16:08 UTC, Thormod commented on exercise_3/index.js
> +let searchparam = '';
delete this variable in order to use functions parameters

2021-03-16 16:16 UTC, Thormod approved these changes, later dismissed

2021-03-16 16:24 UTC, Thormod approved these changes

2021-03-16 16:25 UTC, merged